import { LandingHeader } from "@/components/landing-header";
import { Link } from "wouter";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Shield, Lock, Server, Scale, Eye } from "lucide-react";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-slate-50 pt-[124px] px-4 md:px-8 font-sans">
      <LandingHeader />
      <div className="max-w-4xl mx-auto">
        <div className="mb-8 mt-12">
          <Link href="/">
            <Button variant="ghost" className="gap-2 pl-0 hover:bg-transparent hover:text-primary transition-colors">
              <ArrowLeft className="h-4 w-4" />
              Back to Home
            </Button>
          </Link>
        </div>

        <div className="mb-10">
          <h1 className="text-4xl font-bold tracking-tight mb-3 text-slate-900">Privacy Policy & AI Transparency</h1>
          <p className="text-muted-foreground">Last Updated: January 18, 2026</p>
        </div>

        <div className="grid gap-8">

          {/* SECTION 1: GOVERNANCE (MANDATORY FOR QUEBEC LAW 25) */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold flex items-center gap-2 text-slate-800">
              <Shield className="h-6 w-6 text-primary" />
              1. Governance & Privacy Officer
            </h2>
            <Card className="border-slate-200 shadow-sm">
              <CardContent className="p-6">
                <p className="mb-4 text-slate-600 leading-relaxed">
                  In compliance with <strong>Quebec Law 25</strong> (Act to modernize legislative provisions as regards the protection of personal information), Doculoom (operating as RoomReimagine AI) has designated a Privacy Officer responsible for data protection compliance.
                </p>
                <div className="bg-slate-100 p-5 rounded-lg border border-slate-200">
                  <p className="font-semibold text-slate-900">Olivier Lepage Dumont</p>
                  <p className="text-sm text-slate-500">Founder / Privacy Officer</p>
                  <div className="mt-4 pt-4 border-t border-slate-200/60">
                    <p className="text-xs text-muted-foreground uppercase tracking-wider mb-1">Contact for Privacy Requests</p>
                    <a href="mailto:privacy@doculoom.io" className="text-primary hover:underline font-medium">
                      privacy@doculoom.io
                    </a>
                  </div>
                </div>
              </CardContent>
            </Card>
          </section>

          {/* SECTION 2: AI TRANSPARENCY (MANDATORY FOR BILL C-27) */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold flex items-center gap-2 text-slate-800">
              <Server className="h-6 w-6 text-primary" />
              2. Use of Generative AI (Bill C-27)
            </h2>
            <div className="bg-white p-6 rounded-lg border border-slate-200 shadow-sm prose max-w-none text-slate-600">
              <p>
                This application is classified as a "High-Impact System" under the <em>Artificial Intelligence and Data Act (AIDA)</em>. We are committed to transparency regarding how your content is processed.
              </p>

              <div className="grid md:grid-cols-2 gap-6 mt-6">
                <div>
                  <h3 className="text-lg font-medium text-slate-900 mb-2 flex items-center gap-2">
                    <Eye className="w-4 h-4 text-primary" /> Input Processing
                  </h3>
                  <p className="text-sm">
                    Room photos you upload are processed securely via <strong>Google Gemini 3 Pro</strong>. These images are used strictly for the purpose of generating your design request. We do <strong>not</strong> use your private room photos to train public AI models.
                  </p>
                </div>

                <div>
                  <h3 className="text-lg font-medium text-slate-900 mb-2 flex items-center gap-2">
                    <Scale className="w-4 h-4 text-primary" /> Content Authenticity
                  </h3>
                  <p className="text-sm">
                    Every image generated by our system contains <strong>invisible digital watermarks (SynthID/C2PA)</strong> embedded in the metadata. This ensures that content created by AI can be machine-identified, fulfilling our obligations under Canadian federal law.
                  </p>
                </div>
              </div>
            </div>
          </section>

          {/* SECTION 3: DATA RIGHTS & LOCATION */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold flex items-center gap-2 text-slate-800">
              <Lock className="h-6 w-6 text-primary" />
              3. Your Data Rights
            </h2>
            <div className="bg-white p-6 rounded-lg border border-slate-200 shadow-sm text-slate-600">
              <p className="mb-4">
                Your data is stored securely on cloud infrastructure located in <strong>North America (Canada/USA)</strong>. Under applicable laws, you hold the following rights:
              </p>
              <ul className="space-y-3">
                <li className="flex gap-3">
                  <div className="h-6 w-6 rounded-full bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-xs font-bold text-primary">1</span>
                  </div>
                  <span>
                    <strong>Right to Access & Portability:</strong> You may download a copy of all your generated designs and prompt history in a structured format (JSON) directly from your user dashboard.
                  </span>
                </li>
                <li className="flex gap-3">
                  <div className="h-6 w-6 rounded-full bg-destructive/10 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-xs font-bold text-destructive">2</span>
                  </div>
                  <span>
                    <strong>Right to Erasure ("Right to be Forgotten"):</strong> You may permanently delete your account and all associated images from our servers at any time. This action is irreversible.
                  </span>
                </li>
                <li className="flex gap-3">
                  <div className="h-6 w-6 rounded-full bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-xs font-bold text-primary">3</span>
                  </div>
                  <span>
                    <strong>Consent Withdrawal:</strong> You may withdraw your consent for data processing by deleting your account. Note that this terminates your access to the service.
                  </span>
                </li>
              </ul>
            </div>
          </section>

        </div>

        <footer className="mt-20 pt-8 border-t border-slate-200 text-center text-sm text-muted-foreground">
          <div className="flex flex-col items-center gap-2">
            <p>© 2026 Doculoom (RoomReimagine AI). All rights reserved.</p>
            <p className="text-xs">
              Registered in Quebec, Canada • NEQ available upon request
            </p>
          </div>
        </footer>
      </div>
    </div>
  );
}